from setuptools import setup

setup(name='PyBrokerly',
    version='1.0.0',
    description='Simple interaction with the brokerly bot api.',
    url='',
    author='Brokerly',
    author_email='support@brokerly.com',
    packages=['brokerly'],
    install_requires=['requests'],
      python_requires='>=3.5',
      classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Environment :: Console',
        'Environment :: Web Environment',
        'Intended Audience :: End Users/Desktop',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: Apache Software License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3 :: Only',
        'Topic :: Internet',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
)